# $NetBSD$

DISTNAME=	gnupg2-as-gpg-1.0
CATEGORIES=	meta-pkgs
MASTER_SITES=	# empty

MAINTAINER=	pkgsrc-maintainer@global-wire.fi
COMMENT=	Provide the gpg command for gnupg2
LICENSE=	2-clause-bsd

DEPENDS+=	gnupg2>=2.2.40:../../security/gnupg2

# Provides gpg
CONFLICTS+=	gnupg-1.*

META_PACKAGE=	yes

.include "../../mk/bsd.pkg.mk"
