# $NetBSD$

DISTNAME=	gw-mail-2.2
CATEGORIES=	meta-pkgs
MASTER_SITES=	# empty

MAINTAINER=	pkgsrc-maintainer@global-wire.fi
COMMENT=	Tools for interactive email use
LICENSE=	2-clause-bsd

DEPENDS+=	gw-base>=2.0:../../zz/gw-base

DEPENDS+=	gnupg2>=2.2.40:../../security/gnupg2
DEPENDS+=	lynx>=2.8.9:../../www/lynx
DEPENDS+=	mutt>=2.0.7:../../mail/mutt

META_PACKAGE=	yes

.include "../../mk/bsd.pkg.mk"
