# $NetBSD$

DISTNAME=	gw-mail-2.0
CATEGORIES=	meta-pkgs
MASTER_SITES=	# empty

MAINTAINER=	pkgsrc-maintainer@global-wire.fi
COMMENT=	Development environment tools

DEPENDS+=	gw-base>=2.0:../../gw/gw-base

DEPENDS+=	lynx>=2.8.9:../../www/lynx
DEPENDS+=	mutt>=2.0.7:../../mail/mutt

META_PACKAGE=	yes

.include "../../mk/bsd.pkg.mk"
